package calculator

import (
	"fmt"
)

// CalculationInput represents the parameters required to run the retirement projection.
type CalculationInput struct {
	CurrentAge                     int     `json:"current_age"`
	RetirementAge                  int     `json:"retirement_age"`
	LifeExpectancy                 int     `json:"life_expectancy"`
	CurrentMonthlyExpenses         float64 `json:"current_monthly_expenses"`
	CurrentSavings                 float64 `json:"current_savings"`
	ExpectedInflationRate          float64 `json:"expected_inflation_rate"`
	ExpectedReturnBeforeRetirement float64 `json:"expected_return_before_retirement"`
	ExpectedReturnDuringRetirement float64 `json:"expected_return_during_retirement"`
}

// YearlyProjection represents the account status at the end of each year during the accumulation phase.
type YearlyProjection struct {
	Year            int     `json:"year"`
	Age             int     `json:"age"`
	StartingBalance float64 `json:"starting_balance"`
	Contributions   float64 `json:"contributions"`
	Growth          float64 `json:"growth"`
	EndingBalance   float64 `json:"ending_balance"`
}

// YearlyRetirementProjection represents the account status at the end of each year during the retirement phase.
type YearlyRetirementProjection struct {
	Year            int     `json:"year"`
	Age             int     `json:"age"`
	StartingBalance float64 `json:"starting_balance"`
	Withdrawal      float64 `json:"withdrawal"`
	Growth          float64 `json:"growth"`
	EndingBalance   float64 `json:"ending_balance"`
}

// CalculationOutput represents the structured report generated by the retirement projection.
type CalculationOutput struct {
	YearsToRetirement           int                          `json:"years_to_retirement"`
	RetirementDurationYears     int                          `json:"retirement_duration_years"`
	AnnualExpenseNow            float64                      `json:"annual_expense_now"`
	AnnualExpenseAtRetirement   float64                      `json:"annual_expense_at_retirement"`
	TargetNestEgg               float64                      `json:"target_nest_egg"`
	ProjectedSavingsFromCurrent float64                      `json:"projected_savings_from_current"`
	NestEggShortfall            float64                      `json:"nest_egg_shortfall"`
	RequiredAnnualSavings       float64                      `json:"required_annual_savings"`
	RequiredMonthlySavings      float64                      `json:"required_monthly_savings"`
	Projections                 []YearlyProjection           `json:"projections"`
	RetirementProjections       []YearlyRetirementProjection `json:"retirement_projections"`
	Notes                       []string                     `json:"notes"`
}

// GenerateReport orchestrates all calculations to produce the retirement projection report.
func GenerateReport(input CalculationInput) CalculationOutput {
	// 1. Calculate durations
	yearsToRetire := input.RetirementAge - input.CurrentAge
	if yearsToRetire < 0 {
		yearsToRetire = 0
	}
	retirementDuration := input.LifeExpectancy - input.RetirementAge
	if retirementDuration < 0 {
		retirementDuration = 0
	}

	// 2. Annual expenses calculations
	annualExpenseNow := input.CurrentMonthlyExpenses * 12.0
	annualExpenseAtRetirement := AdjustForInflation(annualExpenseNow, input.ExpectedInflationRate, yearsToRetire)

	// 3. Nest egg calculation
	targetNestEgg := CalculateAnnuityDuePV(
		annualExpenseAtRetirement,
		input.ExpectedInflationRate,
		input.ExpectedReturnDuringRetirement,
		retirementDuration,
	)

	// 4. Projected savings from current principal
	projectedSavingsFromCurrent := CalculateFutureValue(
		input.CurrentSavings,
		input.ExpectedReturnBeforeRetirement,
		yearsToRetire,
	)

	// 5. Shortfall and savings required
	shortfall := targetNestEgg - projectedSavingsFromCurrent
	if shortfall < 0 {
		shortfall = 0
	}

	requiredAnnualSavings, requiredMonthlySavings := CalculateRequiredSavings(
		shortfall,
		input.ExpectedReturnBeforeRetirement,
		yearsToRetire,
	)

	// 6. Generate year-by-year accumulation projections
	projections := make([]YearlyProjection, 0, yearsToRetire)
	currentBalance := input.CurrentSavings

	for t := 1; t <= yearsToRetire; t++ {
		starting := currentBalance
		growth := starting * input.ExpectedReturnBeforeRetirement
		contrib := requiredAnnualSavings

		ending := starting + growth + contrib
		projections = append(projections, YearlyProjection{
			Year:            t,
			Age:             input.CurrentAge + t,
			StartingBalance: starting,
			Contributions:   contrib,
			Growth:          growth,
			EndingBalance:   ending,
		})
		currentBalance = ending
	}

	// 7. Generate year-by-year retirement projections
	retirementProjections := make([]YearlyRetirementProjection, 0, retirementDuration)
	// Start with the actual accumulated balance or the target nest egg, whichever is larger
	retireBalance := targetNestEgg
	if currentBalance > targetNestEgg {
		retireBalance = currentBalance
	}

	for t := 1; t <= retirementDuration; t++ {
		starting := retireBalance

		// Withdrawal occurs at the beginning of the year (annuity due) and grows with inflation each year
		withdrawal := AdjustForInflation(annualExpenseAtRetirement, input.ExpectedInflationRate, t-1)

		actualWithdrawal := withdrawal
		if starting < actualWithdrawal {
			actualWithdrawal = starting
		}

		remaining := starting - actualWithdrawal
		growth := remaining * input.ExpectedReturnDuringRetirement
		ending := remaining + growth

		retirementProjections = append(retirementProjections, YearlyRetirementProjection{
			Year:            t,
			Age:             input.RetirementAge + t,
			StartingBalance: starting,
			Withdrawal:      actualWithdrawal,
			Growth:          growth,
			EndingBalance:   ending,
		})
		retireBalance = ending
	}

	// 8. Construct assumption notes
	notes := buildNotes(input, yearsToRetire, annualExpenseNow, annualExpenseAtRetirement, targetNestEgg, projectedSavingsFromCurrent, shortfall, requiredAnnualSavings, requiredMonthlySavings)

	return CalculationOutput{
		YearsToRetirement:           yearsToRetire,
		RetirementDurationYears:     retirementDuration,
		AnnualExpenseNow:            annualExpenseNow,
		AnnualExpenseAtRetirement:   annualExpenseAtRetirement,
		TargetNestEgg:               targetNestEgg,
		ProjectedSavingsFromCurrent: projectedSavingsFromCurrent,
		NestEggShortfall:            shortfall,
		RequiredAnnualSavings:       requiredAnnualSavings,
		RequiredMonthlySavings:      requiredMonthlySavings,
		Projections:                 projections,
		RetirementProjections:       retirementProjections,
		Notes:                       notes,
	}
}

// buildNotes helper to construct qualitative description of retirement planning assumptions
func buildNotes(
	input CalculationInput,
	yearsToRetire int,
	annualExpenseNow float64,
	annualExpenseAtRetirement float64,
	targetNestEgg float64,
	projectedSavingsFromCurrent float64,
	shortfall float64,
	requiredAnnualSavings float64,
	requiredMonthlySavings float64,
) []string {
	var notes []string

	notes = append(notes, fmt.Sprintf("Inflation: A constant annual inflation rate of %.2f%% is assumed for both pre-retirement and retirement phases.", input.ExpectedInflationRate*100))
	notes = append(notes, fmt.Sprintf("Lifestyle Costs: Current lifestyle expenses of $%.2f/month ($%.2f/year) adjust to $%.2f/year at retirement age %d due to cumulative inflation over %d years.",
		input.CurrentMonthlyExpenses, annualExpenseNow, annualExpenseAtRetirement, input.RetirementAge, yearsToRetire))

	notes = append(notes, fmt.Sprintf("Rates of Return: We assume an investment rate of return of %.2f%% during the accumulation phase, and a more conservative %.2f%% during retirement.",
		input.ExpectedReturnBeforeRetirement*100, input.ExpectedReturnDuringRetirement*100))

	notes = append(notes, fmt.Sprintf("Nest Egg Model: The target nest egg of $%.2f uses the annuity-due model (withdrawals at the beginning of each year) and adjusts withdrawals for inflation during retirement to maintain purchasing power.",
		targetNestEgg))

	notes = append(notes, fmt.Sprintf("Current Savings: Your current savings of $%.2f are projected to grow to $%.2f at retirement age %d, leaving a retirement shortfall of $%.2f.",
		input.CurrentSavings, projectedSavingsFromCurrent, input.RetirementAge, shortfall))

	if shortfall > 0 {
		notes = append(notes, fmt.Sprintf("Required Savings: To close the shortfall, you must save either $%.2f annually (deposited at the end of each year) or $%.2f monthly (using the mathematically equivalent effective monthly rate of %.4f%%).",
			requiredAnnualSavings, requiredMonthlySavings, CalculateEffectiveMonthlyRate(input.ExpectedReturnBeforeRetirement)*100))
	} else {
		notes = append(notes, "Savings Shortfall: No additional savings are required. Your current savings alone are projected to meet or exceed your target nest egg.")
	}

	return notes
}
