# Generated by Django 4.2.30 on 2026-04-11 10:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('primary', 'Primary'), ('partner', 'Partner'), ('child_minor', 'Child (Minor)'), ('child_teen', 'Child (Teen)'), ('dependent', 'Dependent')], default='primary', max_length=20)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('co_owner', 'Co-owner'), ('viewer', 'Viewer'), ('trustee', 'Trustee')], default='owner', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('avatar_color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('cpf', 'CPF'), ('bank', 'Bank Account'), ('equity', 'Equities'), ('property', 'Property'), ('crypto', 'Crypto'), ('insurance', 'Insurance (Cash Value)'), ('alternatives', 'Alternatives')], max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acquisition_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('growth_rate', models.DecimalField(decimal_places=4, default=0, help_text='Annual growth rate as decimal (e.g. 0.07 = 7%)', max_digits=6)),
                ('liquidity_score', models.IntegerField(default=5, help_text='Liquidity score 1-10')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-current_value'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Simulation', max_length=200)),
                ('simulation_type', models.CharField(choices=[('retirement', 'Retirement Projection'), ('fire', 'FIRE Analysis'), ('education', 'Education Fund'), ('property_upgrade', 'Property Upgrade')], default='retirement', max_length=30)),
                ('scenario_params', models.JSONField(default=dict, help_text='Input parameters for the simulation')),
                ('results', models.JSONField(blank=True, help_text='Computed results stored as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='api.account')),
            ],
            options={
                'db_table': 'simulations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('liability_type', models.CharField(choices=[('mortgage', 'Mortgage'), ('car_loan', 'Car Loan'), ('student_loan', 'Student Loan'), ('credit_card', 'Credit Card'), ('personal_loan', 'Personal Loan')], default='personal_loan', max_length=20)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Annual interest rate as decimal (e.g. 0.025 = 2.5%)', max_digits=6)),
                ('tenure_months', models.IntegerField(help_text='Total loan tenure in months')),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_liabilities', to='api.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='api.account')),
            ],
            options={
                'db_table': 'liabilities',
                'ordering': ['-outstanding_balance'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('income_type', models.CharField(choices=[('salary', 'Salary'), ('bonus', 'Bonus'), ('dividends', 'Dividends'), ('rental', 'Rental Income'), ('side_income', 'Side Income'), ('cpf_contribution', 'CPF Contribution'), ('other', 'Other')], default='salary', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_off', 'One-off')], default='monthly', max_length=20)),
                ('growth_rate', models.DecimalField(decimal_places=4, default=0, help_text='Annual growth rate as decimal', max_digits=6)),
                ('volatility', models.DecimalField(decimal_places=4, default=0, help_text='Income volatility/uncertainty factor', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='api.account')),
            ],
            options={
                'db_table': 'incomes',
                'ordering': ['-amount'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('family', 'Family'), ('lifestyle', 'Lifestyle'), ('one_off', 'One-off')], default='variable', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_off', 'One-off')], default='monthly', max_length=20)),
                ('inflation_rate', models.DecimalField(decimal_places=4, default=0.02, help_text='Expected annual inflation for this expense', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.account')),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Other accounts that share this expense', related_name='shared_expenses', to='api.account')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-amount'],
            },
        ),
        migrations.CreateModel(
            name='DistributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage to distribute', max_digits=5)),
                ('unlock_age', models.IntegerField(blank=True, help_text='Age at which this distribution unlocks', null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rules', to='api.asset')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_rules', to='api.account')),
            ],
            options={
                'db_table': 'distribution_rules',
            },
        ),
        migrations.CreateModel(
            name='AssetOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100, help_text='Percentage of asset owned by this account (0-100)', max_digits=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_ownerships', to='api.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='api.asset')),
            ],
            options={
                'db_table': 'asset_ownerships',
                'unique_together': {('asset', 'account')},
            },
        ),
    ]
