# Generated by Django 4.2.30 on 2026-04-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='company',
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_off', 'One-off')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('employment', 'Employment')], default='salary', max_length=30),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('income_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.income')),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('has_cpf', models.BooleanField(default=False)),
                ('start_dt', models.DateField()),
                ('end_dt', models.DateField(null=True)),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_growth_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
            ],
            options={
                'db_table': 'employments',
            },
            bases=('api.income',),
        ),
    ]
