# Generated by Django 4.2.30 on 2026-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='liquidity_score',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='notes',
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(default='SGD', max_length=3),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('equity', 'Equities'), ('property', 'Property'), ('crypto', 'Crypto'), ('insurance', 'Insurance (Cash Value)'), ('alternatives', 'Alternatives'), ('cpf_oa', 'CPF Ordinary Account'), ('cpf_sa', 'CPF Special Account'), ('cpf_ma', 'CPF Medisave Account'), ('cpf_ra', 'CPF Retirement Account')], max_length=20),
        ),
    ]
