# Generated by Django 4.2.30 on 2026-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_asset_liquidity_score_remove_asset_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('equity', 'Equities'), ('cpf_oa', 'CPF Ordinary Account'), ('cpf_sa', 'CPF Special Account'), ('cpf_ma', 'CPF Medisave Account'), ('cpf_ra', 'CPF Retirement Account')], max_length=20),
        ),
    ]
