# Generated by Django 4.2.30 on 2026-04-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_income_company_income_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='api.employment')),
            ],
            options={
                'db_table': 'employment_bonuses',
                'ordering': ['month'],
            },
        ),
    ]
