# Generated by Django 4.2.30 on 2026-04-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cpf_ma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpf_oa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpf_ra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpf_sa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('equity', 'Equities'), ('cpf', 'CPF')], max_length=20),
        ),
    ]
