# Generated by Django 4.2.30 on 2026-04-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employmentbonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='simulation_type',
            field=models.CharField(choices=[('retirement', 'Retirement Projection'), ('fire', 'FIRE Analysis'), ('education', 'Education Fund'), ('property_upgrade', 'Property Upgrade'), ('tax', 'Tax Simulation')], default='retirement', max_length=30),
        ),
    ]
