# Generated by Django 4.2.30 on 2026-04-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_asset_cpf_ma_asset_cpf_oa_asset_cpf_ra_asset_cpf_sa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='growth_rate',
        ),
    ]
