# Generated by Django 4.2.30 on 2026-04-12 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_asset_growth_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='valuation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AssetValuationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cpf_oa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cpf_sa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cpf_ma', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cpf_ra', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_history', to='api.asset')),
            ],
            options={
                'db_table': 'asset_valuation_history',
                'ordering': ['-valuation_date', '-created_at'],
                'unique_together': {('asset', 'valuation_date')},
            },
        ),
    ]
