# Generated by Django 4.2.30 on 2026-04-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_asset_valuation_date_assetvaluationhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetvaluationhistory',
            unique_together=set(),
        ),
    ]
