# Generated by Django 4.2.30 on 2026-04-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_assetvaluationhistory_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-valuation_date', '-id']},
        ),
    ]
