# Generated by Django 4.2.30 on 2026-04-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_asset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetvaluationhistory',
            name='acquisition_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
